///*
// * Timer1.h
// *
// *  Created on: Oct 29, 2023
// *      Author: user
// */
//
//#ifndef INC_TIMER1_H_
//#define INC_TIMER1_H_
//
//#include"MCU_HW.h"
//
//
//typedef enum
//{
//	NORMAL_MODE,PWM_PHASE_CORRECT_8_BIT,PWM_PHASE_CORRECT_9_BIT,PWM_PHASE_CORRECT_10_BIT,CTC_MODE_1,FAST_PWM_8_BIT,FAST_PWM_9_BIT,FAST_PWM_10_BIT,PWM_PHASE_FREQ_CORRECT_1,PWM_PHASE_FREQ_CORRECT_2,PWM_PHASE_CORRECT_1,PWM_PHASE_CORRECT_2,CTC_MODE_2,RESERVED,FAST_PWM_1,FAST_PWM_2
//}TIMER1_MODES;
//
//typedef enum
//{
//	NORMAL_1,TOGGLE_OC0,CLEAR_OC0,SET_OC0
//}NON_PWM_MODE;
//
//typedef enum
//{
//	NORMAL_2,RESERVED_2,NON_INVERTING_MODE,INVERTING_MODE
//}PWM_MODE_1;
//
//typedef enum
//{
//	NO_CLK,CLK_DIV_1,CLK_DIV_8,CLK_DIV_64,CLK_DIV_256,CLK_DIV_1024,CLK_ON_FALLING,CLK_ON_RISING
//}PRESCALER;
//
//typedef enum
//{
//	RELOAD_VALUE,COMPARE_VALUE
//}RELOAD_VALUES;
//
//
//
//typedef struct
//{
//	TIMER1_MODES TIMER0_MODES;
//	NON_PWM_MODE NON_PWM_MODE;
//	PWM_MODE_1 PWM_MODE;
//	PRESCALER PRESCALER;
//	RELOAD_VALUES VALUE;
//
//}TIMER1_CONFIG;
//
//
//
//#endif /* INC_TIMER1_H_ */
